base_url = "https://mucinoab.github.io"

theme = "even"
default_language = 'es'
compile_sass = true
title = "Bruno A. Muci単o"
generate_feed = true

taxonomies = [
    {name = "categories", rss = false},
    {name = "tags", rss = false},
]

# TODO multilingual 
languages = [
    {code = 'en'}, 
]

[extra]
author = "Bruno A. Muci単o"

even_menu = [
    {url = "$BASE_URL/en", name = "English"},
    {url = "https://raw.githubusercontent.com/mucinoab/mucinoab.github.io/dev/extras/Bruno_Muci単o_Resume.pdf", name = "CV"},
    {url = "$BASE_URL/contacto", name = "Contacto"},
]

even_title = "Bruno A. Muci単o"

#katex_enable = true
#katex_auto_render = true
